import type { Mission } from '@/types';

export const mockMissions: Mission[] = [
    {
        id: '1',
        title: 'Healthcare Accessibility Survey',
        description: 'Help us understand healthcare access in your area. Share your experience with local health facilities and suggest improvements.',
        constituency: 'KATHMANDU-3',
        category: 'health',
        status: 'active',
        country: 'Nepal',
        bannerColor: '#FFE4E6',
        startDate: new Date('2026-03-01'),
        totalParticipants: 342,
        isFeatured: true,
        actions: [
            { id: 'a1', type: 'vote', label: 'Vote on Priority Areas', points: 150, icon: '🗳️' },
            { id: 'a2', type: 'comment', label: 'Share Your Experience', points: 50, icon: '💬' },
            { id: 'a3', type: 'proposal', label: 'Submit Improvement Proposal', points: 100, icon: '📝' },
            { id: 'a4', type: 'upload', label: 'Upload Photo Evidence', points: 75, icon: '📸' },
        ],
    },
    {
        id: '2',
        title: 'Road Infrastructure Assessment',
        description: 'Document road conditions and safety issues in your neighborhood. Your input will help prioritize infrastructure repairs.',
        constituency: 'LALITPUR-2',
        category: 'infrastructure',
        status: 'active',
        country: 'Nepal',
        bannerColor: '#FEF3C7',
        startDate: new Date('2026-02-28'),
        totalParticipants: 218,
        isFeatured: true,
        actions: [
            { id: 'b1', type: 'upload', label: 'Report Road Issue', points: 100, icon: '📸' },
            { id: 'b2', type: 'vote', label: 'Vote on Priority Roads', points: 120, icon: '🗳️' },
            { id: 'b3', type: 'comment', label: 'Add Comments', points: 40, icon: '💬' },
            { id: 'b4', type: 'share', label: 'Share with Community', points: 30, icon: '🔗' },
        ],
    },
    {
        id: '3',
        title: 'School Quality Feedback',
        description: 'Rate your experience with local schools. Help improve education quality through community feedback and suggestions.',
        constituency: 'BHAKTAPUR-1',
        category: 'education',
        status: 'active',
        country: 'Nepal',
        bannerColor: '#EEF2FF',
        startDate: new Date('2026-02-25'),
        totalParticipants: 156,
        actions: [
            { id: 'c1', type: 'survey', label: 'Complete Survey', points: 180, icon: '📊' },
            { id: 'c2', type: 'comment', label: 'Provide Feedback', points: 60, icon: '💬' },
            { id: 'c3', type: 'proposal', label: 'Suggest Improvements', points: 90, icon: '📝' },
            { id: 'c4', type: 'share', label: 'Invite Parents', points: 40, icon: '🔗' },
        ],
    },
    {
        id: '4',
        title: 'Waste Management Initiative',
        description: 'Join the effort to improve waste collection and recycling in your area. Track waste disposal issues and suggest solutions.',
        constituency: 'KATHMANDU-3',
        category: 'environment',
        status: 'active',
        country: 'Nepal',
        bannerColor: '#DCFCE7',
        startDate: new Date('2026-02-20'),
        totalParticipants: 289,
        actions: [
            { id: 'd1', type: 'upload', label: 'Report Waste Issue', points: 80, icon: '📸' },
            { id: 'd2', type: 'vote', label: 'Vote on Solutions', points: 100, icon: '🗳️' },
            { id: 'd3', type: 'proposal', label: 'Propose New Collection Point', points: 120, icon: '📝' },
            { id: 'd4', type: 'comment', label: 'Share Ideas', points: 50, icon: '💬' },
        ],
    },
    {
        id: '5',
        title: 'Budget Transparency Review',
        description: 'Review and comment on local budget allocations. Help ensure transparent and accountable use of public funds.',
        constituency: 'POKHARA-1',
        category: 'governance',
        status: 'active',
        country: 'Nepal',
        bannerColor: '#F3E8FF',
        startDate: new Date('2026-02-15'),
        totalParticipants: 412,
        actions: [
            { id: 'e1', type: 'vote', label: 'Vote on Budget Priorities', points: 200, icon: '🗳️' },
            { id: 'e2', type: 'comment', label: 'Add Comments', points: 70, icon: '💬' },
            { id: 'e3', type: 'proposal', label: 'Suggest Allocation Changes', points: 150, icon: '📝' },
        ],
    },
    {
        id: '6',
        title: 'Community Park Development',
        description: 'Share your ideas for the new community park. Vote on features and help design a space for everyone to enjoy.',
        constituency: 'LALITPUR-2',
        category: 'social',
        status: 'active',
        country: 'Nepal',
        bannerColor: '#FFE4E6',
        startDate: new Date('2026-02-10'),
        totalParticipants: 195,
        actions: [
            { id: 'f1', type: 'vote', label: 'Vote on Park Features', points: 130, icon: '🗳️' },
            { id: 'f2', type: 'proposal', label: 'Submit Design Ideas', points: 110, icon: '📝' },
            { id: 'f3', type: 'comment', label: 'Discuss with Community', points: 55, icon: '💬' },
            { id: 'f4', type: 'share', label: 'Share Survey', points: 35, icon: '🔗' },
        ],
    },
];

export const mockStats = {
    yourPoints: 2450,
    currentStreak: 12,
    weeklyRank: 12,
    missionsCompleted: 24,
};
