import type { Poll } from '@/types';

const generateTrend = (labels: string[], dates: string[]) => {
    const data = [];
    for (let i = 0; i < dates.length; i++) {
        const point: Record<string, number | string> = { date: dates[i] };
        let remaining = 100;
        for (let j = 0; j < labels.length - 1; j++) {
            const base = j === 0 ? 50 + i * 3 : 30 - i * 2;
            const v = Math.max(2, Math.min(remaining - 2, base + Math.floor(Math.random() * 6)));
            point[labels[j]] = v;
            remaining -= v;
        }
        point[labels[labels.length - 1]] = Math.max(1, remaining);
        data.push(point);
    }
    return data;
};

const dates = ['Feb 23', 'Feb 24', 'Feb 25', 'Feb 26', 'Feb 27', 'Mar 1', 'Mar 2'];

export const mockPolls: Poll[] = [
    {
        id: '1',
        pid: 504,
        title: 'Who should represent Jhapa-5?',
        question: 'Who should represent Jhapa-5?',
        description: 'Cast your vote for the representative of Jhapa-5 constituency in the upcoming elections.',
        category: 'political',
        type: 'referendum',
        status: 'active',
        constituency: 'JHAPA-5',
        country: 'Nepal',
        bannerLabel: 'JHAPA-5',
        creator: '@superteamnepal',
        createdAt: '6 days ago',
        endsAt: '2026-03-06',
        daysLeft: 4,
        totalVotes: 510,
        options: [
            { id: 'o1', label: 'Balen Shah', votes: 434, percentage: 85, color: '#E11D48', image: '/balen.jpeg' },
            { id: 'o2', label: 'K.P. Sharma Oli', votes: 51, percentage: 10, color: '#818CF8' },
            { id: 'o3', label: 'Others', votes: 25, percentage: 5, color: '#94A3B8' },
        ],
        trendData: [
            { date: 'Feb 23', o1: 0, o2: 0, o3: 0 },
            { date: 'Feb 24', o1: 72, o2: 18, o3: 10 },
            { date: 'Feb 25', o1: 74, o2: 16, o3: 10 },
            { date: 'Feb 26', o1: 76, o2: 14, o3: 10 },
            { date: 'Feb 27', o1: 78, o2: 13, o3: 9 },
            { date: 'Mar 1', o1: 82, o2: 11, o3: 7 },
            { date: 'Mar 2', o1: 85, o2: 10, o3: 5 },
        ],
        comments: [
            { id: 'c1', author: 'Aayush Sharma', walletAddress: 'aayush...7x3k', text: 'Balen has done great work for Kathmandu. He deserves to represent Jhapa-5 as well!', likes: 14, createdAt: '2 days ago' },
            { id: 'c2', author: 'Priya Thapa', walletAddress: 'priya...9m2s', text: 'I think we need new leadership. The old parties have failed us repeatedly.', likes: 8, createdAt: '3 days ago' },
            { id: 'c3', author: 'Rajan K.', walletAddress: 'rajan...4t5a', text: 'Transparency and accountability should be the priority. Whoever wins must deliver on promises.', likes: 21, createdAt: '5 days ago' },
        ],
        rules: [
            'One vote per wallet address.',
            'Votes are final and cannot be changed.',
            'Results are publicly visible in real time.',
            'Earn 5 JMT points for casting your vote.',
            'Earn 2 JMT points for each comment.',
            'Share this poll to earn 0.01 SOL directly.',
        ],
        pointsForVoting: 5,
        pointsForComment: 2,
        pointsForShare: 0,
        solRewardForShare: 0.01,
    },
    {
        id: '2',
        pid: 505,
        title: 'Who should represent Gulmi-1?',
        question: 'Who should represent Gulmi-1?',
        description: 'Vote for the best candidate to represent Gulmi-1 in the upcoming elections.',
        category: 'political',
        type: 'candidate',
        status: 'active',
        constituency: 'GULMI-1',
        country: 'Nepal',
        bannerLabel: 'GULMI-1',
        creator: '@superteamnepal',
        createdAt: '6 days ago',
        endsAt: '2026-03-06',
        daysLeft: 4,
        totalVotes: 229,
        options: [
            { id: 'o1', label: 'Sagar Dhakal', votes: 215, percentage: 94, color: '#E11D48' },
            { id: 'o2', label: 'Pradeep Gyawali', votes: 7, percentage: 3, color: '#818CF8' },
            { id: 'o3', label: 'Others', votes: 7, percentage: 3, color: '#94A3B8' },
        ],
        trendData: [
            { date: 'Feb 23', o1: 0, o2: 0, o3: 0 },
            { date: 'Feb 24', o1: 88, o2: 7, o3: 5 },
            { date: 'Feb 25', o1: 90, o2: 6, o3: 4 },
            { date: 'Feb 26', o1: 91, o2: 5, o3: 4 },
            { date: 'Feb 27', o1: 92, o2: 5, o3: 3 },
            { date: 'Mar 1', o1: 93, o2: 4, o3: 3 },
            { date: 'Mar 2', o1: 94, o2: 3, o3: 3 },
        ],
        comments: [
            { id: 'c1', author: 'Sunita Limbu', walletAddress: 'suni...8b2c', text: 'Sagar Dhakal has been working hard for our constituency. Clear choice!', likes: 18, createdAt: '1 day ago' },
        ],
        rules: [
            'One vote per wallet address.',
            'Results are publicly visible in real time.',
            'Earn 5 JMT points for casting your vote.',
            'Earn 2 JMT points for each comment.',
            'Share to earn 0.01 SOL directly.',
        ],
        pointsForVoting: 5,
        pointsForComment: 2,
        pointsForShare: 0,
        solRewardForShare: 0.01,
    },
    {
        id: '3',
        pid: 506,
        title: 'Who should represent Sarlahi-4?',
        question: 'Who should represent Sarlahi-4?',
        category: 'political',
        type: 'candidate',
        status: 'active',
        constituency: 'SARLAHI-4',
        country: 'Nepal',
        bannerLabel: 'SARLAHI-4',
        creator: '@superteamnepal',
        createdAt: '6 days ago',
        endsAt: '2026-03-06',
        daysLeft: 4,
        totalVotes: 151,
        options: [
            { id: 'o1', label: 'Amaresh Kumar Singh', votes: 85, percentage: 56, color: '#E11D48' },
            { id: 'o2', label: 'Gagan Thapa', votes: 54, percentage: 36, color: '#818CF8' },
            { id: 'o3', label: 'Others', votes: 12, percentage: 8, color: '#94A3B8' },
        ],
        trendData: [
            { date: 'Feb 23', o1: 0, o2: 0, o3: 0 },
            { date: 'Feb 24', o1: 45, o2: 40, o3: 15 },
            { date: 'Feb 25', o1: 48, o2: 40, o3: 12 },
            { date: 'Feb 26', o1: 50, o2: 39, o3: 11 },
            { date: 'Feb 27', o1: 53, o2: 37, o3: 10 },
            { date: 'Mar 1', o1: 54, o2: 37, o3: 9 },
            { date: 'Mar 2', o1: 56, o2: 36, o3: 8 },
        ],
        comments: [],
        rules: [
            'One vote per wallet address.',
            'Earn 5 JMT points for casting your vote.',
            'Share to earn 0.01 SOL directly.',
        ],
        pointsForVoting: 5,
        pointsForComment: 2,
        pointsForShare: 0,
        solRewardForShare: 0.01,
    },
    {
        id: '4',
        pid: 507,
        title: 'Who should represent Kathmandu-3?',
        question: 'Who should represent Kathmandu-3?',
        category: 'political',
        type: 'candidate',
        status: 'active',
        constituency: 'KATHMANDU-3',
        country: 'Nepal',
        bannerLabel: 'KATHMANDU-3',
        creator: '@superteamnepal',
        createdAt: '6 days ago',
        endsAt: '2026-03-06',
        daysLeft: 4,
        totalVotes: 102,
        options: [
            { id: 'o1', label: 'Kulman Ghising', votes: 77, percentage: 75, color: '#E11D48' },
            { id: 'o2', label: 'Rajunath Pandey', votes: 21, percentage: 21, color: '#818CF8' },
            { id: 'o3', label: 'Others', votes: 4, percentage: 4, color: '#94A3B8' },
        ],
        trendData: [
            { date: 'Feb 23', o1: 0, o2: 0, o3: 0 },
            { date: 'Feb 24', o1: 65, o2: 28, o3: 7 },
            { date: 'Feb 25', o1: 68, o2: 26, o3: 6 },
            { date: 'Feb 26', o1: 70, o2: 24, o3: 6 },
            { date: 'Feb 27', o1: 72, o2: 23, o3: 5 },
            { date: 'Mar 1', o1: 74, o2: 22, o3: 4 },
            { date: 'Mar 2', o1: 75, o2: 21, o3: 4 },
        ],
        comments: [
            { id: 'c1', author: 'Kulman Fan', walletAddress: 'kulm...3f5q', text: 'Finally some real leadership in Kathmandu!', likes: 9, createdAt: '2 days ago' },
        ],
        rules: [
            'One vote per wallet address.',
            'Earn 5 JMT points for casting your vote.',
            'Share to earn 0.01 SOL directly.',
        ],
        pointsForVoting: 5,
        pointsForComment: 2,
        pointsForShare: 0,
        solRewardForShare: 0.01,
    },
    {
        id: '5',
        pid: 508,
        title: 'Should Butwal Kalika Campus make internal assessment marks fully transparent?',
        question: 'Should Butwal Kalika Campus make internal assessment marks fully transparent?',
        description: 'A poll to gauge public opinion on whether academic institutions should publish full internal marking breakdowns.',
        category: 'education',
        type: 'referendum',
        status: 'active',
        constituency: 'BUTWAL',
        country: 'Nepal',
        bannerLabel: 'EDUCATION',
        creator: '@superteamnepal',
        createdAt: '6 days ago',
        endsAt: '2026-03-10',
        daysLeft: 8,
        totalVotes: 98,
        options: [
            { id: 'o1', label: 'Publish full marking breakdown', votes: 62, percentage: 63, color: '#818CF8' },
            { id: 'o2', label: 'Show individual marks only', votes: 21, percentage: 21, color: '#FB923C' },
            { id: 'o3', label: 'Keep current system', votes: 15, percentage: 15, color: '#34D399' },
        ],
        trendData: [
            { date: 'Feb 23', o1: 0, o2: 0, o3: 0 },
            { date: 'Feb 24', o1: 72, o2: 25, o3: 3 },
            { date: 'Feb 25', o1: 74, o2: 22, o3: 4 },
            { date: 'Feb 26', o1: 74, o2: 21, o3: 5 },
            { date: 'Feb 27', o1: 76, o2: 18, o3: 6 },
            { date: 'Mar 1', o1: 65, o2: 20, o3: 15 },
            { date: 'Mar 2', o1: 63, o2: 21, o3: 16 },
        ],
        comments: [
            { id: 'c1', author: 'Bikash Rai', walletAddress: 'bika...9x2p', text: 'Transparency is crucial for academic trust. Students deserve to know how they are evaluated!', likes: 12, createdAt: '4 days ago' },
            { id: 'c2', author: 'Anita Paudel', walletAddress: 'anit...7k1m', text: 'Some privacy in marking is also important. Full breakdown might cause unnecessary disputes.', likes: 7, createdAt: '5 days ago' },
            { id: 'c3', author: 'Hari Prasad', walletAddress: 'hari...5n8j', text: 'The current system is broken. We need full transparency to hold teachers accountable.', likes: 19, createdAt: '6 days ago' },
        ],
        rules: [
            'One vote per wallet address.',
            'Votes are final and cannot be changed.',
            'Results are publicly visible in real time.',
            'Earn 3 JMT points for casting your vote.',
            'Earn 1 JMT point for each accepted comment.',
            'Share this poll to earn 0.01 SOL directly.',
        ],
        pointsForVoting: 3,
        pointsForComment: 1,
        pointsForShare: 0,
        solRewardForShare: 0.01,
    },
    {
        id: '6',
        pid: 509,
        title: 'Should Kathmandu implement paid parking zones?',
        question: 'Should Kathmandu implement paid parking zones in the city center?',
        description: 'Help decide whether Kathmandu should introduce paid parking to reduce traffic congestion.',
        category: 'infrastructure',
        type: 'opinion',
        status: 'active',
        constituency: 'KATHMANDU',
        country: 'Nepal',
        bannerLabel: 'INFRASTRUCTURE',
        creator: '@janamatcivic',
        createdAt: '3 days ago',
        endsAt: '2026-03-09',
        daysLeft: 7,
        totalVotes: 203,
        options: [
            { id: 'o1', label: 'Yes, implement paid parking', votes: 122, percentage: 60, color: '#E11D48' },
            { id: 'o2', label: 'No, keep it free', votes: 61, percentage: 30, color: '#818CF8' },
            { id: 'o3', label: 'Hybrid model', votes: 20, percentage: 10, color: '#34D399' },
        ],
        trendData: [
            { date: 'Feb 28', o1: 55, o2: 35, o3: 10 },
            { date: 'Mar 1', o1: 57, o2: 33, o3: 10 },
            { date: 'Mar 2', o1: 60, o2: 30, o3: 10 },
        ],
        comments: [],
        rules: [
            'One vote per wallet address.',
            'Earn 3 JMT points for casting your vote.',
            'Earn 1 JMT point for each comment.',
            'Share to earn 0.01 SOL directly.',
        ],
        pointsForVoting: 3,
        pointsForComment: 1,
        pointsForShare: 0,
        solRewardForShare: 0.01,
    },
    {
        id: '7',
        pid: 510,
        title: 'Best approach to manage Bagmati River pollution?',
        question: 'What is the best approach to manage Bagmati River pollution?',
        category: 'environment',
        type: 'survey',
        status: 'active',
        constituency: 'KATHMANDU',
        country: 'Nepal',
        bannerLabel: 'ENVIRONMENT',
        creator: '@greennepal',
        createdAt: '5 days ago',
        endsAt: '2026-03-12',
        daysLeft: 10,
        totalVotes: 318,
        options: [
            { id: 'o1', label: 'Industrial discharge ban', votes: 159, percentage: 50, color: '#34D399' },
            { id: 'o2', label: 'Community cleanup drives', votes: 96, percentage: 30, color: '#60A5FA' },
            { id: 'o3', label: 'Government-led restoration', votes: 63, percentage: 20, color: '#FBBF24' },
        ],
        trendData: [
            { date: 'Feb 25', o1: 48, o2: 32, o3: 20 },
            { date: 'Feb 26', o1: 49, o2: 31, o3: 20 },
            { date: 'Feb 27', o1: 50, o2: 30, o3: 20 },
            { date: 'Mar 1', o1: 50, o2: 30, o3: 20 },
            { date: 'Mar 2', o1: 50, o2: 30, o3: 20 },
        ],
        comments: [],
        rules: [
            'One vote per wallet address.',
            'Earn 3 JMT points for casting your vote.',
            'Share to earn 0.01 SOL directly.',
        ],
        pointsForVoting: 3,
        pointsForComment: 1,
        pointsForShare: 0,
        solRewardForShare: 0.01,
    },
    {
        id: '8',
        pid: 511,
        title: 'Should Nepal legalize cryptocurrency trading?',
        question: 'Should Nepal legalize and regulate cryptocurrency trading?',
        category: 'governance',
        type: 'referendum',
        status: 'active',
        constituency: 'NATIONAL',
        country: 'Nepal',
        bannerLabel: 'GOVERNANCE',
        creator: '@cryptonepal',
        createdAt: '2 days ago',
        endsAt: '2026-03-15',
        daysLeft: 13,
        totalVotes: 512,
        options: [
            { id: 'o1', label: 'Yes, legalize & regulate', votes: 358, percentage: 70, color: '#818CF8' },
            { id: 'o2', label: 'No, keep current ban', votes: 77, percentage: 15, color: '#E11D48' },
            { id: 'o3', label: 'Study further first', votes: 77, percentage: 15, color: '#94A3B8' },
        ],
        trendData: [
            { date: 'Mar 1', o1: 68, o2: 16, o3: 16 },
            { date: 'Mar 2', o1: 70, o2: 15, o3: 15 },
        ],
        comments: [],
        rules: [
            'One vote per wallet address.',
            'Earn 4 JMT points for casting your vote.',
            'Earn 2 JMT points for each comment.',
            'Share to earn 0.01 SOL directly.',
        ],
        pointsForVoting: 4,
        pointsForComment: 2,
        pointsForShare: 0,
        solRewardForShare: 0.01,
    },
];

export const mockReferrals = [
    { id: 'r1', refereeAddress: 'abc...1234', status: 'completed' as const, pointsEarned: 5, completedAt: '2026-02-28' },
    { id: 'r2', refereeAddress: 'def...5678', status: 'completed' as const, pointsEarned: 5, completedAt: '2026-03-01' },
    { id: 'r3', refereeAddress: null, status: 'pending' as const, pointsEarned: 0, completedAt: undefined },
];
